name: depostok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  sidebarx: ^0.17.1
  geolocator: ^12.0.0
  flutter_osm_plugin: ^1.0.5
  flutter_hooks: ^0.20.5
  pointer_interceptor: ^0.10.1+1
  popup_menu: ^2.0.0
  two_dimensional_scrollables: ^0.3.0
  table_calendar: ^3.0.1
  intl: ^0.17.0
  charts_flutter: ^0.12.0

  flutter_map: ^7.0.1
  flutter_ringtone_player: ^4.0.0+3

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  latlong2: ^0.9.1

  url_launcher: ^6.1.8
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/
     - asset/ca/
     - asset/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
